# Generated by Django 5.1.7 on 2025-04-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_rename_tarefa_tarefamodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefamodel',
            name='data_conclusao',
        ),
        migrations.AddField(
            model_name='tarefamodel',
            name='titulo',
            field=models.CharField(default='Titulo Padräo', max_length=100),
            preserve_default=False,
        ),
    ]
